package com.mycompany.mapita.modelo;
// Generated 8/02/2019 02:10:16 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private MarcadorId id;
     private Usuario usuario;

    public Marcador() {
    }

    public Marcador(MarcadorId id, Usuario usuario) {
       this.id = id;
       this.usuario = usuario;
    }
   
    public MarcadorId getId() {
        return this.id;
    }
    
    public void setId(MarcadorId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


